name: APK Yapici
on: [push]

jobs:
  apk-yap:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Java Kur
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Flutter Kur (Eski Saglam Surum)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Kutuphaneleri Yukle
        run: |
          pip install -r requirements.txt
          pip install --upgrade flet  # <--- BU SATIR FLET'İ GÜNCELLER VE HATAYI ÇÖZER

      - name: APK Derle
        # Artık Flet güncel olduğu için bu komut çalışacaktır:
        run: flet build apk --product-name "Hilal_kpss" --icon icon.png --verbose

      - name: Dosyayi Yukle
        uses: actions/upload-artifact@v4
        with:
          name: Saglam-APK
          path: build/apk/app-release.apk
